# the name of the workflow
name: Python CI

# Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Jobs that run in the workflow
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup python 3.10 environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the tests
      - name: Run tests
        run: pytest